### ISSUE TITLE
wont work with Vaadin 7.5.10 (and Vaadin designer).

### ISSUE THREAD

**Issue by m0rkeulv** [florianschmitt/ext-token-field#7]
Tried to add this component to an existing view using Vaadin designer. It behaves normally inside the designer and i can set properties etc, however when i try to run my code and test the compoenent, it fails with the following stacktrace. 

`com.vaadin.event.ListenerMethod$MethodException: Invocation of method attach in com.explicatis.ext_token_field.ExtTokenField$2 failed.
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:528) ~[vaadin-server-7.5.10.jar:7.5.10]
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198) ~[vaadin-server-7.5.10.jar:7.5.10]
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161) ~[vaadin-server-7.5.10.jar:7.5.10]
    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1003) ~[vaadin-server-7.5.10.jar:7.5.10]
    at com.vaadin.server.AbstractClientConnector.attach(AbstractClientConnector.java:613) ~[vaadin-server-7.5.10.jar:7.5.10]
    at com.vaadin.ui.AbstractComponent.attach(AbstractComponent.java:669) ~[vaadin-server-7.5.10.jar:7.5.10]
    at com.vaadin.ui.AbstractField.attach(AbstractField.java:1389) ~[vaadin-server-7.5.10.jar:7.5.10]
    at com.vaadin.server.AbstractClientConnector.attach(AbstractClientConnector.java:616) ~[vaadin-server-7.5.10.jar:7.5.10]
    at com.vaadin.ui.AbstractComponent.attach(AbstractComponent.java:669) ~[vaadin-server-7.5.10.jar:7.5.10]
    at com.vaadin.server.AbstractClientConnector.attach(AbstractClientConnector.java:616) ~[vaadin-server-7.5.10.jar:7.5.10]
    at com.vaadin.ui.AbstractComponent.attach(AbstractComponent.java:669) ~[vaadin-server-7.5.10.jar:7.5.10]
    at com.vaadin.server.AbstractClientConnector.attach(AbstractClientConnector.java:616) ~[vaadin-server-7.5.10.jar:7.5.10]
    at com.vaadin.ui.AbstractComponent.attach(AbstractComponent.java:669) ~[vaadin-server-7.5.10.jar:7.5.10]
    at com.vaadin.server.AbstractClientConnector.attach(AbstractClientConnector.java:616) ~[vaadin-server-7.5.10.jar:7.5.10]
    at com.vaadin.ui.AbstractComponent.attach(AbstractComponent.java:669) ~[vaadin-server-7.5.10.jar:7.5.10]
    at com.vaadin.server.AbstractClientConnector.attach(AbstractClientConnector.java:616) ~[vaadin-server-7.5.10.jar:7.5.10]
    at com.vaadin.ui.AbstractComponent.attach(AbstractComponent.java:669) ~[vaadin-server-7.5.10.jar:7.5.10]
    at com.vaadin.ui.AbstractComponent.setParent(AbstractComponent.java:576) ~[vaadin-server-7.5.10.jar:7.5.10]
    at com.vaadin.ui.AbstractSingleComponentContainer.setContent(AbstractSingleComponentContainer.java:150) ~[vaadin-server-7.5.10.jar:7.5.10]
    at com.vaadin.navigator.Navigator$SingleComponentContainerViewDisplay.showView(Navigator.java:224) ~[vaadin-server-7.5.10.jar:7.5.10]
    at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:575) ~[vaadin-server-7.5.10.jar:7.5.10]
    at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:527) ~[vaadin-server-7.5.10.jar:7.5.10]`

**Comment by florianschmitt** [comment]
Hey, 
did you maybe forgot to specify an inputField (ComboBox) or inputButton (Button)? 
Right now, there is a hacky RuntimeException thrown, if you didn't set it and attach it to a layout:

``` java
            @Override
            public void attach(AttachEvent event)
            {
                if (!hasInputButton() && !hasInputField())
                    throw new RuntimeException("no input field nor input button set");
            }
```

**Comment by m0rkeulv** [comment]
I dont see any way to bind those values this using Vaadin Designer, so i am try to add it by code.
I am kind of new to vaadin so it might also be caused some mistake on my end,  my code implementation is currently getting a vaadin error, so i guess ill have too look more closely on how to include new addons.

"Widgetset 'com.vaadin.DefaultWidgetSet' does not contain implementation for com.explicatis.ext_token_field.ExtTokenField. ....."

**Comment by florianschmitt** [comment]
Well, I didn't use the designer yet, so I cannot help you with the integration. Maybe you should try it without the designer first. 

> "Widgetset 'com.vaadin.DefaultWidgetSet' does not contain implementation for com.explicatis.ext_token_field.ExtTokenField. ....."

This message indicates, that you didn't compile the widgetset (yet). The client-side widgetset, needs to be recompiled for every add-on you add. Look for example [here](https://vaadin.com/docs/-/part/framework/gwt/gwt-eclipse.html).
